Add 2019-September OKRs
microsoft-healthcare-madison/team pull request #1
Opened 2019-07-03 16:38 UTC by jmandel

2019-07-10 17:50 UTC, jmandel commented
@GinoCanessa Do you get alerts for these?

2019-07-10 18:31 UTC, GinoCanessa commented
I got this with the mention.  I haven’t seen anything else.

From: Josh Mandel <notifications@github.com>
Sent: Wednesday, July 10, 2019 12:50 PM
To: microsoft-healthcare-madison/team <team@noreply.github.com>
Cc: Gino Canessa <Gino.Canessa@microsoft.com>; Mention <mention@noreply.github.com>
Subject: Re: [microsoft-healthcare-madison/team] Add 2019-September OKRs (#1)


@GinoCanessa<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGinoCanessa&data=02%7C01%7Cgino.canessa%40microsoft.com%7Cf3e747abb1d444775d7608d7055f0fbd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636983778149939590&sdata=YnH0eyqi4WtdoV0dQV4JZn1jZlIvOK86%2FUmZ1uiPdNs%3D&reserved=0> Do you get alerts for these?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft-healthcare-madison%2Fteam%2Fpull%2F1%3Femail_source%3Dnotifications%26email_token%3DAMAU75NMSL67T6QZQ5GLFV3P6YONLA5CNFSM4H5HVDU2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZUHOBI%23issuecomment-510162693&data=02%7C01%7Cgino.canessa%40microsoft.com%7Cf3e747abb1d444775d7608d7055f0fbd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636983778149939590&sdata=9%2F82VGg6RtpsKlyKoRYQc2Ieud%2BhtlXNVaS1O9ys72E%3D&reserved=0>, or mute the thread<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMAU75OIEGIC4HJQAD5DZYLP6YONLANCNFSM4H5HVDUQ&data=02%7C01%7Cgino.canessa%40microsoft.com%7Cf3e747abb1d444775d7608d7055f0fbd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636983778149949545&sdata=Si6DH%2FLSp6%2FAD08dAyHhj%2FG6ZXit68ctxBsW2ic%2BNwk%3D&reserved=0>.

2019-07-18 14:22 UTC, GinoCanessa approved these changes

2019-07-18 14:29 UTC, GinoCanessa requested changes

2019-07-18 14:29 UTC, GinoCanessa commented on okrs-2019-september.md
> +
```suggestion
P0: Ensure that all necessary changes to Subscription and Topic are merged into the main FHIR build before Sunday, August 11 (to make the R5 Connectathon snapshot for tooling).
```

2019-07-18 14:34 UTC, merged